// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package UserRpc // import "./"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password" json:"Password,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email" json:"Email,omitempty"`
	Age                  int64    `protobuf:"varint,5,opt,name=Age" json:"Age,omitempty"`
	Tel                  string   `protobuf:"bytes,6,opt,name=Tel" json:"Tel,omitempty"`
	Addr                 string   `protobuf:"bytes,7,opt,name=Addr" json:"Addr,omitempty"`
	Card                 string   `protobuf:"bytes,8,opt,name=Card" json:"Card,omitempty"`
	CreateTime           int64    `protobuf:"varint,9,opt,name=CreateTime" json:"CreateTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,10,opt,name=UpdateTime" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_df7f612da5663b11, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *User) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *User) GetCard() string {
	if m != nil {
		return m.Card
	}
	return ""
}

func (m *User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *User) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_df7f612da5663b11, []int{1}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_df7f612da5663b11, []int{2}
}
func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (dst *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(dst, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_df7f612da5663b11, []int{3}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_df7f612da5663b11, []int{4}
}
func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(dst, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_df7f612da5663b11, []int{5}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_df7f612da5663b11, []int{6}
}
func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(dst, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DelUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserRequest) Reset()         { *m = DelUserRequest{} }
func (m *DelUserRequest) String() string { return proto.CompactTextString(m) }
func (*DelUserRequest) ProtoMessage()    {}
func (*DelUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_df7f612da5663b11, []int{7}
}
func (m *DelUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserRequest.Unmarshal(m, b)
}
func (m *DelUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserRequest.Marshal(b, m, deterministic)
}
func (dst *DelUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserRequest.Merge(dst, src)
}
func (m *DelUserRequest) XXX_Size() int {
	return xxx_messageInfo_DelUserRequest.Size(m)
}
func (m *DelUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserRequest proto.InternalMessageInfo

func (m *DelUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DelUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserResponse) Reset()         { *m = DelUserResponse{} }
func (m *DelUserResponse) String() string { return proto.CompactTextString(m) }
func (*DelUserResponse) ProtoMessage()    {}
func (*DelUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_df7f612da5663b11, []int{8}
}
func (m *DelUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserResponse.Unmarshal(m, b)
}
func (m *DelUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserResponse.Marshal(b, m, deterministic)
}
func (dst *DelUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserResponse.Merge(dst, src)
}
func (m *DelUserResponse) XXX_Size() int {
	return xxx_messageInfo_DelUserResponse.Size(m)
}
func (m *DelUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserResponse proto.InternalMessageInfo

func (m *DelUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user.CreateUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "user.UpdateUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "user.GetUserResponse")
	proto.RegisterType((*DelUserRequest)(nil), "user.DelUserRequest")
	proto.RegisterType((*DelUserResponse)(nil), "user.DelUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	DelUser(ctx context.Context, in *DelUserRequest, opts ...grpc.CallOption) (*DelUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := grpc.Invoke(ctx, "/user.UserService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := grpc.Invoke(ctx, "/user.UserService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := grpc.Invoke(ctx, "/user.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DelUser(ctx context.Context, in *DelUserRequest, opts ...grpc.CallOption) (*DelUserResponse, error) {
	out := new(DelUserResponse)
	err := grpc.Invoke(ctx, "/user.UserService/DelUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	DelUser(context.Context, *DelUserRequest) (*DelUserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DelUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DelUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DelUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DelUser(ctx, req.(*DelUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "DelUser",
			Handler:    _UserService_DelUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_df7f612da5663b11) }

var fileDescriptor_user_df7f612da5663b11 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x6b, 0xea, 0x40,
	0x10, 0x26, 0x1a, 0x35, 0x8e, 0x0f, 0x7d, 0x6f, 0xf1, 0xf1, 0x96, 0x1c, 0x44, 0xc2, 0x3b, 0x08,
	0x85, 0x94, 0x2a, 0xf4, 0xd2, 0x83, 0x58, 0x5b, 0x5a, 0x6f, 0x25, 0xd5, 0x4b, 0x6f, 0x69, 0x76,
	0x28, 0x01, 0x35, 0xe9, 0x6e, 0xd2, 0xfe, 0xed, 0xfe, 0x83, 0x96, 0xdd, 0xcd, 0xc6, 0xa8, 0x05,
	0xe9, 0x6d, 0xe6, 0xfb, 0x66, 0xbe, 0x71, 0xbf, 0xcf, 0x00, 0xe4, 0x02, 0xb9, 0x9f, 0xf2, 0x24,
	0x4b, 0x88, 0x2d, 0x6b, 0xef, 0xc3, 0x02, 0x7b, 0x25, 0x90, 0x93, 0x2e, 0xd4, 0x16, 0x8c, 0x5a,
	0x43, 0x6b, 0x54, 0x0f, 0x6a, 0x0b, 0x46, 0x5c, 0x70, 0x24, 0xbe, 0x0d, 0x37, 0x48, 0x6b, 0x43,
	0x6b, 0xd4, 0x0e, 0xca, 0x5e, 0x72, 0x0f, 0xa1, 0x10, 0xef, 0x09, 0x67, 0xb4, 0xae, 0x39, 0xd3,
	0x93, 0x3e, 0x34, 0x6e, 0x37, 0x61, 0xbc, 0xa6, 0xb6, 0x22, 0x74, 0x43, 0x7e, 0x43, 0x7d, 0xf6,
	0x82, 0xb4, 0xa1, 0xe4, 0x65, 0x29, 0x91, 0x25, 0xae, 0x69, 0x53, 0x4d, 0xc9, 0x92, 0x10, 0xb0,
	0x67, 0x8c, 0x71, 0xda, 0x52, 0x90, 0xaa, 0x25, 0x36, 0x0f, 0x39, 0xa3, 0x8e, 0xc6, 0x64, 0x4d,
	0x06, 0x00, 0x73, 0x8e, 0x61, 0x86, 0xcb, 0x78, 0x83, 0xb4, 0xad, 0x24, 0x2b, 0x88, 0xe4, 0x57,
	0x29, 0x33, 0x3c, 0x68, 0x7e, 0x87, 0x78, 0x13, 0xf8, 0xa3, 0xa7, 0xe5, 0x7b, 0x02, 0x7c, 0xcd,
	0x51, 0x64, 0x64, 0x00, 0xca, 0x0f, 0x65, 0x40, 0x67, 0x0c, 0xbe, 0x32, 0x4a, 0x0d, 0x68, 0x9f,
	0xfe, 0x03, 0xa9, 0x2e, 0x89, 0x34, 0xd9, 0x0a, 0x94, 0xa6, 0xc5, 0xa5, 0x69, 0x31, 0x93, 0xd2,
	0xfa, 0xd0, 0x4f, 0xa4, 0x7d, 0x20, 0xd5, 0xa5, 0x42, 0x9a, 0x42, 0x4b, 0xe4, 0x51, 0x84, 0x42,
	0xa8, 0x45, 0x27, 0x30, 0xad, 0x77, 0x0f, 0xdd, 0x3b, 0xcc, 0xaa, 0x17, 0x5c, 0x70, 0x72, 0x93,
	0x95, 0xa5, 0xf3, 0xc8, 0x2b, 0x59, 0xa5, 0x26, 0xab, 0x22, 0x47, 0xd3, 0x7b, 0x17, 0xd0, 0x2b,
	0x95, 0x8a, 0xb3, 0xa7, 0x7e, 0xec, 0x10, 0xba, 0x37, 0xb8, 0xae, 0x1e, 0x3f, 0xf4, 0xe0, 0x0c,
	0x7a, 0xe5, 0xc4, 0xa9, 0xb7, 0x8c, 0x3f, 0x2d, 0xe8, 0xc8, 0xd1, 0x47, 0xe4, 0x6f, 0x71, 0x84,
	0x64, 0x6a, 0xb2, 0x55, 0xff, 0xc9, 0x7f, 0xfa, 0xfc, 0x51, 0x5a, 0x2e, 0x3d, 0x26, 0x8a, 0x53,
	0x53, 0x13, 0x7e, 0x55, 0xe0, 0x28, 0x13, 0x23, 0xf0, 0x8d, 0xef, 0x97, 0xd0, 0x2a, 0x3c, 0x21,
	0x7d, 0x3d, 0xb4, 0x6f, 0xb6, 0xfb, 0xf7, 0x00, 0xdd, 0xed, 0x15, 0xcf, 0x36, 0x7b, 0xfb, 0x3e,
	0x99, 0xbd, 0x03, 0x6f, 0xae, 0x7f, 0x3d, 0x81, 0x7f, 0x7e, 0xa5, 0xa0, 0x34, 0x7a, 0x6e, 0xaa,
	0x6f, 0x73, 0xf2, 0x15, 0x00, 0x00, 0xff, 0xff, 0x15, 0x39, 0xbc, 0xed, 0xa9, 0x03, 0x00, 0x00,
}
