// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: imMsg.proto

package ImMsgRpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FormUserId uint64 `protobuf:"varint,2,opt,name=FormUserId,proto3" json:"FormUserId,omitempty"`
	ToUserId   uint64 `protobuf:"varint,3,opt,name=ToUserId,proto3" json:"ToUserId,omitempty"`
	Content    string `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	MsgImg     string `protobuf:"bytes,5,opt,name=MsgImg,proto3" json:"MsgImg,omitempty"`
	SendTime   uint64 `protobuf:"varint,6,opt,name=SendTime,proto3" json:"SendTime,omitempty"`
	CreateTime uint64 `protobuf:"varint,7,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime uint64 `protobuf:"varint,8,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
}

func (x *ImMsg) Reset() {
	*x = ImMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImMsg) ProtoMessage() {}

func (x *ImMsg) ProtoReflect() protoreflect.Message {
	mi := &file_imMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImMsg.ProtoReflect.Descriptor instead.
func (*ImMsg) Descriptor() ([]byte, []int) {
	return file_imMsg_proto_rawDescGZIP(), []int{0}
}

func (x *ImMsg) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImMsg) GetFormUserId() uint64 {
	if x != nil {
		return x.FormUserId
	}
	return 0
}

func (x *ImMsg) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *ImMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ImMsg) GetMsgImg() string {
	if x != nil {
		return x.MsgImg
	}
	return ""
}

func (x *ImMsg) GetSendTime() uint64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *ImMsg) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ImMsg) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type CreateMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImMsg *ImMsg `protobuf:"bytes,1,opt,name=imMsg,proto3" json:"imMsg,omitempty"`
}

func (x *CreateMsgRequest) Reset() {
	*x = CreateMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMsgRequest) ProtoMessage() {}

func (x *CreateMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMsgRequest.ProtoReflect.Descriptor instead.
func (*CreateMsgRequest) Descriptor() ([]byte, []int) {
	return file_imMsg_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMsgRequest) GetImMsg() *ImMsg {
	if x != nil {
		return x.ImMsg
	}
	return nil
}

type CreateMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CreateMsgResponse) Reset() {
	*x = CreateMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imMsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMsgResponse) ProtoMessage() {}

func (x *CreateMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_imMsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMsgResponse.ProtoReflect.Descriptor instead.
func (*CreateMsgResponse) Descriptor() ([]byte, []int) {
	return file_imMsg_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMsgResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormUserId uint64 `protobuf:"varint,1,opt,name=formUserId,proto3" json:"formUserId,omitempty"`
	ToUserId   uint64 `protobuf:"varint,2,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	PageSize   uint64 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNum    uint64 `protobuf:"varint,4,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
}

func (x *GetMsgRequest) Reset() {
	*x = GetMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imMsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMsgRequest) ProtoMessage() {}

func (x *GetMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imMsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMsgRequest.ProtoReflect.Descriptor instead.
func (*GetMsgRequest) Descriptor() ([]byte, []int) {
	return file_imMsg_proto_rawDescGZIP(), []int{3}
}

func (x *GetMsgRequest) GetFormUserId() uint64 {
	if x != nil {
		return x.FormUserId
	}
	return 0
}

func (x *GetMsgRequest) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *GetMsgRequest) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMsgRequest) GetPageNum() uint64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

type GetMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize uint64   `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNum  uint64   `protobuf:"varint,2,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	ImMsg    []*ImMsg `protobuf:"bytes,3,rep,name=imMsg,proto3" json:"imMsg,omitempty"`
}

func (x *GetMsgResponse) Reset() {
	*x = GetMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imMsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMsgResponse) ProtoMessage() {}

func (x *GetMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_imMsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMsgResponse.ProtoReflect.Descriptor instead.
func (*GetMsgResponse) Descriptor() ([]byte, []int) {
	return file_imMsg_proto_rawDescGZIP(), []int{4}
}

func (x *GetMsgResponse) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMsgResponse) GetPageNum() uint64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetMsgResponse) GetImMsg() []*ImMsg {
	if x != nil {
		return x.ImMsg
	}
	return nil
}

var File_imMsg_proto protoreflect.FileDescriptor

var file_imMsg_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x6d, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x49,
	0x6d, 0x4d, 0x73, 0x67, 0x22, 0xe1, 0x01, 0x0a, 0x05, 0x49, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x46, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x49, 0x6d, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x73, 0x67, 0x49, 0x6d, 0x67, 0x12, 0x1a, 0x0a, 0x08,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05,
	0x69, 0x6d, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x49, 0x6d,
	0x4d, 0x73, 0x67, 0x2e, 0x49, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x05, 0x69, 0x6d, 0x4d, 0x73, 0x67,
	0x22, 0x2d, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x81, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x66, 0x6f, 0x72, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x67,
	0x65, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65,
	0x4e, 0x75, 0x6d, 0x22, 0x6a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x22, 0x0a, 0x05, 0x69,
	0x6d, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x49, 0x6d, 0x4d,
	0x73, 0x67, 0x2e, 0x49, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x05, 0x69, 0x6d, 0x4d, 0x73, 0x67, 0x32,
	0x85, 0x01, 0x0a, 0x0c, 0x49, 0x6d, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3e, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x17, 0x2e,
	0x49, 0x6d, 0x4d, 0x73, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x49, 0x6d, 0x4d, 0x73, 0x67, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x2e, 0x49, 0x6d, 0x4d,
	0x73, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x49, 0x6d, 0x4d, 0x73, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x49, 0x6d,
	0x4d, 0x73, 0x67, 0x52, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_imMsg_proto_rawDescOnce sync.Once
	file_imMsg_proto_rawDescData = file_imMsg_proto_rawDesc
)

func file_imMsg_proto_rawDescGZIP() []byte {
	file_imMsg_proto_rawDescOnce.Do(func() {
		file_imMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_imMsg_proto_rawDescData)
	})
	return file_imMsg_proto_rawDescData
}

var file_imMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_imMsg_proto_goTypes = []interface{}{
	(*ImMsg)(nil),             // 0: ImMsg.ImMsg
	(*CreateMsgRequest)(nil),  // 1: ImMsg.CreateMsgRequest
	(*CreateMsgResponse)(nil), // 2: ImMsg.CreateMsgResponse
	(*GetMsgRequest)(nil),     // 3: ImMsg.GetMsgRequest
	(*GetMsgResponse)(nil),    // 4: ImMsg.GetMsgResponse
}
var file_imMsg_proto_depIdxs = []int32{
	0, // 0: ImMsg.CreateMsgRequest.imMsg:type_name -> ImMsg.ImMsg
	0, // 1: ImMsg.GetMsgResponse.imMsg:type_name -> ImMsg.ImMsg
	1, // 2: ImMsg.ImMsgService.CreateMsg:input_type -> ImMsg.CreateMsgRequest
	3, // 3: ImMsg.ImMsgService.GetMsg:input_type -> ImMsg.GetMsgRequest
	2, // 4: ImMsg.ImMsgService.CreateMsg:output_type -> ImMsg.CreateMsgResponse
	4, // 5: ImMsg.ImMsgService.GetMsg:output_type -> ImMsg.GetMsgResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_imMsg_proto_init() }
func file_imMsg_proto_init() {
	if File_imMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_imMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imMsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imMsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imMsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_imMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imMsg_proto_goTypes,
		DependencyIndexes: file_imMsg_proto_depIdxs,
		MessageInfos:      file_imMsg_proto_msgTypes,
	}.Build()
	File_imMsg_proto = out.File
	file_imMsg_proto_rawDesc = nil
	file_imMsg_proto_goTypes = nil
	file_imMsg_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ImMsgServiceClient is the client API for ImMsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImMsgServiceClient interface {
	CreateMsg(ctx context.Context, in *CreateMsgRequest, opts ...grpc.CallOption) (*CreateMsgResponse, error)
	GetMsg(ctx context.Context, in *GetMsgRequest, opts ...grpc.CallOption) (*GetMsgResponse, error)
}

type imMsgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImMsgServiceClient(cc grpc.ClientConnInterface) ImMsgServiceClient {
	return &imMsgServiceClient{cc}
}

func (c *imMsgServiceClient) CreateMsg(ctx context.Context, in *CreateMsgRequest, opts ...grpc.CallOption) (*CreateMsgResponse, error) {
	out := new(CreateMsgResponse)
	err := c.cc.Invoke(ctx, "/ImMsg.ImMsgService/CreateMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imMsgServiceClient) GetMsg(ctx context.Context, in *GetMsgRequest, opts ...grpc.CallOption) (*GetMsgResponse, error) {
	out := new(GetMsgResponse)
	err := c.cc.Invoke(ctx, "/ImMsg.ImMsgService/GetMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImMsgServiceServer is the server API for ImMsgService service.
type ImMsgServiceServer interface {
	CreateMsg(context.Context, *CreateMsgRequest) (*CreateMsgResponse, error)
	GetMsg(context.Context, *GetMsgRequest) (*GetMsgResponse, error)
}

// UnimplementedImMsgServiceServer can be embedded to have forward compatible implementations.
type UnimplementedImMsgServiceServer struct {
}

func (*UnimplementedImMsgServiceServer) CreateMsg(context.Context, *CreateMsgRequest) (*CreateMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMsg not implemented")
}
func (*UnimplementedImMsgServiceServer) GetMsg(context.Context, *GetMsgRequest) (*GetMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMsg not implemented")
}

func RegisterImMsgServiceServer(s *grpc.Server, srv ImMsgServiceServer) {
	s.RegisterService(&_ImMsgService_serviceDesc, srv)
}

func _ImMsgService_CreateMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImMsgServiceServer).CreateMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ImMsg.ImMsgService/CreateMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImMsgServiceServer).CreateMsg(ctx, req.(*CreateMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImMsgService_GetMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImMsgServiceServer).GetMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ImMsg.ImMsgService/GetMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImMsgServiceServer).GetMsg(ctx, req.(*GetMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImMsgService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ImMsg.ImMsgService",
	HandlerType: (*ImMsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMsg",
			Handler:    _ImMsgService_CreateMsg_Handler,
		},
		{
			MethodName: "GetMsg",
			Handler:    _ImMsgService_GetMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imMsg.proto",
}
